apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dedx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dedx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0052-app
  name: devfile-sample-dedx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dedx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dedx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-dedx@sha256:9b6dce001316dc1b97b528cb922f5a77990dbee3f2db80a4fdd6659437efdf31
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
